platform :ios, '10.0'

use_frameworks!
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ours-curiosity/CTSpecs'

target 'CTNet_Example' do
  pod 'CTNet', :path => '../'

  target 'CTNet_Tests' do
    inherit! :search_paths

    
  end
end
